# Generated by Django 4.2.4 on 2023-08-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongSenseiApp', '0002_mp3file_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp3file',
            name='mp3_file',
            field=models.FileField(upload_to=''),
        ),
    ]
